# Generated by Django 4.0.dev20210517092135 on 2021-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_book_genre_book_genre_remove_cd_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songlist',
            name='song',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='type',
        ),
        migrations.AlterField(
            model_name='cd',
            name='song_list',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterOrderWithRespectTo(
            name='rent',
            order_with_respect_to='user',
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'writer', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='cd',
            unique_together={('song_list', 'genre')},
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='SongList',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='start_date',
        ),
    ]
