# Generated by Django 4.0.dev20210517092135 on 2021-06-12 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_songlist_song_remove_genre_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='created_at',
            new_name='rent_date',
        ),
        migrations.AddField(
            model_name='rent',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
