# Generated by Django 4.0.dev20210517092135 on 2021-06-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_created_at_rent_rent_date_rent_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.band'),
        ),
    ]
